name: Run Script

on:
  schedule:
    - cron: '0 * * * *'  # This runs the script every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # You can specify the version of Node.js here
    - name: Run npm install
      run: npm install
    - name: Run the script
      run: node bsky.js
      env:
        BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
        BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
